### ISSUE TITLE
How to actually run the deploy command

### ISSUE THREAD

**Issue by deckchairlabs** [jakejarvis/firebase-deploy-action#1]
I can see that the default CMD is to list the help for the firebase deploy command, but how do you actually run the deploy command. I've tried the below:

```yaml
- name: Deploy to firebase
  uses: jakejarvis/firebase-deploy-action@master
  with:
    args: deploy
  env:
    FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
```

But I receive 

> Error: Too many arguments. Run firebase help deploy for usage instructions
